 const actionTypes = {
  SAVE_USER: 'SAVE_USER',
  ADD_PRODUCT: 'ADD_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  CLEAR_CART: 'CLEAR_CART',
  SAVE_SHIPPING_ADDRESS: 'SAVE_SHIPPING_ADDRESS'
}

export default actionTypes